replicaCount: 1

postgres:
  name: postgres
  container:
    image: postgres:12.4-alpine
    port: 5432
  replicaCount: 1
  volume:
    name: postgres-database-storage
    pvc:
      name: postgres-pv-claim
    mountPath: /var/lib/pgsql/data
  config:
    name: postgres-config

service:
  type: NodePort
  port: 5432

