---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: django-app
spec:
    replicas: 1
    selector:
       matchLabels:
          app: django-app-kub
    template:
       metadata:
          labels:
             app: django-app-kub
       spec:
          containers:
          - name: backend
            image: aitakynsultan/django-helm:v4
            command: ["/bin/bash","-c"]
            args: ["python manage.py makemigrations && python manage.py migrate && python manage.py runserver"]
            envFrom:
              - configMapRef:
                  name: postgres-configuration
              - secretRef:
                  name: postgres-secrets
            ports:
              - name: web
                containerPort: 80

#                      env:
#                        - name: POSTGRES_HOST
#                          value: postgres
#                        - name: POSTGRES_PORT
#                          value: "5432"
#                        - name: POSTGRES_DB
#                          value: mydb
#                        - name: POSTGRES_USER
#                          value: user
#                        - name: POSTGRES_PASSWORD
#                          value: aiktayn