apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
spec:
  serviceName: "postgres"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.container.image }}
        ports:
        - containerPort: {{ .Values.postgres.container.port }}
          name: postgresdb
        env:
          - name: POSTGRES_DB
            value: mydb
          - name: POSTGRES_USER
            value: user
          - name: POSTGRES_PASSWORD
            value: aitakyn
          - name: POSTGRES_HOST
            value: "postgres"
        volumeMounts:
        - name: postgresdb
          mountPath: {{ .Values.postgres.volume.mountPath }}
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgresdb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi